#! /bin/sh

xrc param/latest

aaa(){
    param:dsl <<A
option:
    -y|--fsdfsd|-o          "Test regex arg1"  <regex_arg1>=888  =~  "[0-9]+"
    -n                      "Test regex arg2"  <regex_arg1>=123  =~  "[0-9]+"

A
    param:run

    no_issue=flase
    new_option="xxx"
    k="kkk"
    p=""
    m="aaa"
    param:option2json has_issues=^no_issue has_wiki=^no_wiki can_comment=^no_comment auto_init=^no_auto_init new_option repoitory l=^^k o=^^p y +m -n
    echo "\nhas_issues: $has_issues\nhas_wiki: $has_wiki\ncan_comment: $can_comment\nauto_init: $auto_init\nnew_option: $new_option\nrepoitory: $repoitory\nl: $l\no: $o\ny: $y\nm: $m\n"
}
aaa