name: docker build
on: 
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
      with: 
        ref: main 
        fetch-depth: 0
    - name: Docker build
      run: |
        docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        docker buildx create --use
        docker buildx build \
          --no-cache \
          --platform linux/arm,linux/arm64,linux/amd64 \
          -f "./docker/alpine/Dockerfile" \
          -t "xcmd/alpine-nightly:latest" . --push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}