name: docker build
on: 
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Docker build
      run: |
        eval "$(curl https://get.x-cmd.com/dev)" || true
        git clone https://github.com/x-cmd/image.git
        cd image
        x image || true
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}