name: 'docker build'
on:
  # workflow_run:
  #   workflows: ["publish x-cmd/x-cmd nightly"]
  #   types:
  #     - completed
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
