name: 'docker build'

on:
  workflow_run:
    workflows: ["publish x-cmd/x-cmd nightly"]
    types:
      - completed
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: |
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
          docker buildx create --use
          bash ./.x-cmd/build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
