name: Publish-Manual
on:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 3
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws pub || true
