name: Package and Publish
on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws pub || true
