name: Publish x-cmd/x-cmd nightly
on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_user: agent-zero
          git_email: 0@x-cmd.com
          code: x ws pub0 || true
